version: "2" # required to adjust maintainability checks
plugins:
  pep8:
    enabled: true
exclude_patterns:
  - "!**/*.py"
  - "contrib/"
  - "eventex/core/static"
  - ".Notebooks/"
  - "google-python-exercises/"
